### ISSUE TITLE
uLSIF: non-negativity by "current_alpha.elem(find(current_alpha < 0)).zeros();"

### ISSUE THREAD

**Issue by ddu10300** [thomvolker/densityratio#19]
Hello,

Thank you for the efficient implementation of the uLSIF. Currently, the parameter can be negative and may lead to negative density ratio in the "ulsif.cpp" with the line `current_alpha =  ulsif_compute_alpha(Hhat, hhat, la);
        alpha.slice(l).col(sig) = current_alpha;`

I was wondering would you consider to handle this by adding `current_alpha.elem(find(current_alpha < 0)).zeros();` like what is done in the "lhss.cpp"?

Thank you!

**Comment by thomvolker** [comment]
Hi,

It is a deliberate choice to not sweep potential problems under the carpet, as rather extreme negative values could indicate problems in the estimation procedure (perhaps the sigma or lambda sequences are not appropriate, or scaling should be implemented). Also, it is rather easy to change these parameters after estimating the model. In R, you could simply use pmax(0, x$alpha) to set the parameters to zero.

In lhss, I made a different choice because the subspace and the parameters are estimated in an alternating fashion, so having negative values here might also affect the subspace, which makes it a bit awkward to change the alpha parameters merely after estimation.

Best,
Thom

**Comment by thomvolker** [comment]
Closing as this is not a software issue but a deliberate choice. Thanks again for your comment!
